create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

create policy "Public can read tasks"
on public.tasks
for select
to anon
using (true);
